**Choleski decomposition**

In [1]:
import numpy as np

#### Solving equations after LU factorization
_Implementation of forward substitution_

In [2]:
def forward_substitution(L, b):
    
    # Get number of rows
    n = L.shape[0]
    
    # Allocating space for the solution vector
    y = np.zeros_like(b, dtype=np.double);
    
    # Here we perform the forward-substitution.  
    # Initializing  with the first row.
    y[0] = b[0] / L[0, 0]
    
    # Looping over rows in reverse (from the bottom  up), 
    # starting with the second to last row, because  the 
    # last row solve was completed in the last step.
    for i in range(1, n):
        y[i] = (b[i] - np.dot(L[i,:i], y[:i])) / L[i,i]
        
    return y

_Implementation of back substitution_

In [3]:
def back_substitution(U, y):
    
    # Number of rows
    n = U.shape[0]
    
    # Allocating space for the solution vector
    x = np.zeros_like(y, dtype=np.double);

    # Here we perform the back-substitution.  
    # Initializing with the last row.
    x[-1] = y[-1] / U[-1, -1]
    
    # Looping over rows in reverse (from the bottom up), 
    # starting with the second to last row, because the 
    # last row solve was completed in the last step.
    for i in range(n-2, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i:], x[i:])) / U[i,i]
        
    return x

#### Overall equation solution

In [4]:
import pprint as pp
def lu_solve(A, b):
    
    L, U = doolittle(A)
    
    print("Lower diagonal matrix: \n")
    pp.pprint(L)
    print('\n')
    print("Upper diagonal matrix: \n")
    pp.pprint(U)
    print('\n')
    
    y = forward_substitution(L, b)
    
    x = back_substitution(U,y)
    print("Solution: \n")
    pp.pprint(x)
    
    return

In [7]:
A = np.array([[1.44,-0.36,5.52,0.00],[-0.36,10.33,-7.78,0.00],[5.52,-7.78,28.40,9.00],[0.00,0.00,9.00,61.00]])
b = np.array([[0.04],[-2.15],[0.0],[0.88]])

In [8]:
from math import sqrt
def cholesky(A):
    """
    Performs a Cholesky decomposition of A, which must 
    be a symmetric and positive definite matrix. The function
    returns the lower variant triangular matrix, L.
    """
    n = len(A)

    # Create zero matrix for L
    L = [[0.0] * n for i in range(n)]

    # Perform the Cholesky decomposition
    for i in range(n):
        for k in range(i+1):
            tmp_sum = sum(L[i][j] * L[k][j] for j in range(k))
            
            if (i == k): # diagonal elements
                L[i][k] = sqrt(A[i][i] - tmp_sum)
            else:
                L[i][k] = (1.0 / L[k][k] * (A[i][k] - tmp_sum))
    return L

Converting to numpy array

In [9]:
X = cholesky(A)
L = np.asarray(X,dtype=float)
L_t = L.transpose()

Overall equation solver (modifying lu_solve(A,b)). Here U = transpose of L

In [10]:
def lu_solve(A, b, L, L_t):
    print("Lower diagonal matrix: \n")
    pp.pprint(L)
    print('\n')
    print("Transpose of lower diagonal matrix: \n")
    pp.pprint(L_t)
    print('\n')
    
    y = forward_substitution(L, b)
    
    x = back_substitution(L_t,y)
    print("Solution: \n")
    pp.pprint(x)
    
    return

In [11]:
lu_solve(A,b,L,L_t)

Lower diagonal matrix: 

array([[ 1.2,  0. ,  0. ,  0. ],
       [-0.3,  3.2,  0. ,  0. ],
       [ 4.6, -2. ,  1.8,  0. ],
       [ 0. ,  0. ,  5. ,  6. ]])


Transpose of lower diagonal matrix: 

array([[ 1.2, -0.3,  4.6,  0. ],
       [ 0. ,  3.2, -2. ,  0. ],
       [ 0. ,  0. ,  1.8,  5. ],
       [ 0. ,  0. ,  0. ,  6. ]])


Solution: 

array([[ 3.09212567],
       [-0.73871706],
       [-0.8475723 ],
       [ 0.13947788]])
