In [2]:
import numpy as np

def GaussElimination_Pivot(A, b):
    """
    Gaussian elimination with partial pivoting.
    input: A is an n x n nonsingular matrix
           b is an n x 1 vector
    output: x is the solution of Ax=b.
    post-condition: A and b have been modified. 
    """
    n =  len(A)
    if b.size != n:
        raise ValueError("Invalid argument: incompatible sizes between A & b.", b.size, n)
    # k represents the current pivot row. Since GE traverses the matrix in the upper 
    # right triangle, we also use k for indicating the k-th diagonal column index.
    for k in range(n-1):
        #Choose largest pivot element below (and including) k
        maxindex = abs(A[k:,k]).argmax() + k
        if A[maxindex, k] == 0:
            raise ValueError("Matrix is singular.")
        #Swap rows
        if maxindex != k:
            A[[k,maxindex]] = A[[maxindex, k]]
            b[[k,maxindex]] = b[[maxindex, k]]
        for row in range(k+1, n):
            multiplier = A[row][k]/A[k][k]
            #the only one in this column since the rest are zero
            A[row][k] = multiplier
            for col in range(k + 1, n):
                A[row][col] = A[row][col] - multiplier*A[k][col]
            #Equation solution column
            b[row] = b[row] - multiplier*b[k]
    print(A)
    print(b)
    x = np.zeros(n)
    k = n-1
    x[k] = b[k]/A[k,k]
    while k >= 0:
        x[k] = (b[k] - np.dot(A[k,k+1:],x[k+1:]))/A[k,k]
        k = k-1
    return x

In [3]:
A = np.array([[1.,2.,2.],[3.,6.,-1.],[1.,3.,1.]])
b = np.array([[21.],[7.],[15.]])
print(GaussElimination_Pivot(A,b))

[[ 3.          6.         -1.        ]
 [ 0.33333333  1.          1.33333333]
 [ 0.33333333  0.          2.33333333]]
[[ 7.        ]
 [12.66666667]
 [18.66666667]]
[1. 2. 8.]
